export const categoryColorsActive = {
  Celkem: '#000000',
  'Nemoci nakažlivé a cizopasné': '#f95d6a',
  'Nemoci ústrojí oběhu krevního': '#ffa600',
  'Rakovina a jiné nádory': '#a05195',
  'Válečné akce a soudní poprava': '#804500',

  'Válečné akce a soudní poprava - muži': '#2A4B8C',
  'Válečné akce a soudní poprava - ženy': '#B90101',

  'Nemoci rheumatické, výživové, žláz s vnitřním vyměšováním, jiné nemoci celkové a avitaminos': '#000000',
  'Nemoci krve a ústrojů krvetvorných': '#11a579',
  'Otravy vleklé': '#3969ac',
  'Nemoci soustavy nervové a smyslových ústrojů': '#f2b701',
  'Nemoci ústrojů dýchacích': '#e73f74',
  'Nemoci ústrojí zažívacího': '#80ba5a',
  'Nemoci ústrojí močového a pohlavního': '#e68310',
  'Nemoci těhotenství, porodu a stavu poporodního': '#e68310',
  'Nemoci kůže a vaziva podkožního': '#008695',
  'Nemoci kostí a ústrojí pohybu': '#cf1c90',
  'Vrozené vady vývojové': '#f97b72',
  'Zvláštní nemoci útlého věku': '#4b4b8f',
  'Stařecká sešlost': '#a5aa99',
  Sebevraždy: '#0ebcbf',
  'Vraždy a zabití': '#5158bb',
  'Úrazy při dopravě': '#9e52aa',
  'Úrazy a otravy mimo dopravu': '#eb4776',
  'Neurčité příčiny smrti': '#f58a5a',
};
