export const categoryColorsActive = {
  Celkem: '#008080',
  'Některé infekční a parazitární nemoci': '#f2b701',
  'Nemoci oběhové soustavy': '#c86092',
  Novotvary: '#643879',
  'Zákonný zákrok a válečné operace': '#996666',
  'Nemoci endokrinní, výživy a přeměny látek': '#379970',
  'Nemoci krve, krvetvorných orgánů a některé poruchy týkající se mechanismu imunity': '#af0063',
  'Nemoci dýchací soustavy': '#47a8b3',
  'Nemoci trávicí soustavy': '#7cb35a',
  'Nemoci močové a pohlavní soustavy': '#e1c699',
  'Těhotenství, porod a šestinedělí': '#fda394',
  'Nemoci kůže a podkožního vaziva': '#d9c2ba',
  'Nemoci svalové a kosterní soustavy a pojivové tkáně': '#80808f',
  'Vrozené vady, deformace a chromosomální abnormality': '#f97b72',
  'Některé stavy vzniklé v perinatálním období': '#fd5994',
  'Úmyslné sebepoškození': '#ed820e',
  'Napadení (útok)': '#e6456b',
  'Dopravní nehody': '#006080',
  'Ostatní vnější příčiny poranění a otrav': '#98aeb6',

  'Příznaky, znaky a abnormální klinické a laboratorní nálezy nezařazené jinde': '#c5cfd0',
  'Nemoci nervové soustavy': '#4363d8',
  'Poruchy duševní a poruchy chování': '#669bcc',
  'Nemoci oka a očních adnex': '#cc6633',
  'Nemoci ucha a bradavkového výběžku': '#fcd297',
  'Komplikace zdravotní péče': '#fca01e',
};
