export const categoryColorsActive = {
  Celkem: '#000000',
  'Některé infekční a parazitární nemoci': '#f95d6a',
  'Nemoci oběhové soustavy': '#ffa600',
  Novotvary: '#a05195',
  'Zákonný zákrok a válečné operace': '#804500',
  'Nemoci endokrinní, výživy a přeměny látek': '#000000',
  'Nemoci krve, krvetvorných orgánů a některé poruchy týkající se mechanismu imunity': '#11a579',
  'Nemoci dýchací soustavy': '#e73f74',
  'Nemoci trávicí soustavy': '#80ba5a',
  'Nemoci močové a pohlavní soustavy': '#e68310',
  'Těhotenství, porod a šestinedělí': '#e68310',
  'Nemoci kůže a podkožního vaziva': '#008695',
  'Nemoci svalové a kosterní soustavy a pojivové tkáně': '#cf1c90',
  'Vrozené vady, deformace a chromosomální abnormality': '#f97b72',
  'Některé stavy vzniklé v perinatálním období': '#4b4b8f',
  'Úmyslné sebepoškození': '#0ebcbf',
  'Napadení (útok)': '#5158bb',
  'Dopravní nehody': '#9e52aa',
  'Ostatní vnější příčiny poranění a otrav': '#eb4776',

  'Příznaky, znaky a abnormální klinické a laboratorní nálezy nezařazené jinde': '#f58a5a',
  'Nemoci nervové soustavy': '#f2b701',
  'Poruchy duševní a poruchy chování': '#f2b701',
  'Nemoci oka a očních adnex': '#f2b701',
  'Nemoci ucha a bradavkového výběžku': '#f2b701',
  'Komplikace zdravotní péče': '#f2b701',
};
