export const categoryColorsActive = {
  Celkem: '#008080',
  'Některé infekční a parazitární nemoci': '#f2b701',
  'Nemoci oběhové soustavy': '#c86092',
  Novotvary: '#643879',
  'Zákonný zákrok a válečné operace': '#996666',
  'Nemoci endokrinní, výživy a přeměny látek': '#379970',
  'Nemoci krve, krvetvorných orgánů a některé poruchy týkající se mechanismu imunity': '#af0063',
  'Nemoci dýchací soustavy': '#47a8b3',
  'Nemoci trávicí soustavy': '#7cb35a',
  'Nemoci močové a pohlavní soustavy': '#e1c699',
  'Těhotenství, porod a šestinedělí': '#fda394',
  'Nemoci kůže a podkožního vaziva': '#d9c2ba',
  'Nemoci svalové a kosterní soustavy a pojivové tkáně': '#80808f',
  'Vrozené vady, deformace a chromosomální abnormality': '#f97b72',
  'Některé stavy vzniklé v perinatálním období': '#fd5994',
  'Úmyslné sebepoškození': '#ed820e',
  'Napadení (útok)': '#e6456b',
  'Dopravní nehody': '#006080',
  'Ostatní vnější příčiny poranění a otrav': '#98aeb6',

  'Příznaky, znaky a abnormální klinické a laboratorní nálezy nezařazené jinde': '#c5cfd0',
  'Nemoci nervové soustavy': '#f2b704363d81',
  'Poruchy duševní a poruchy chování': '#669bcc',
  'Nemoci oka a očních adnex': '#cc6633',
  'Nemoci ucha a bradavkového výběžku': '#fcd297',
  'Komplikace zdravotní péče': '#fca01e',
  // Celkem: '#000000',
  // 'Některé infekční a parazitární nemoci': '#f95d6a',
  // 'Nemoci oběhové soustavy': '#ffa600',
  // Novotvary: '#a05195',
  // 'Zákonný zákrok a válečné operace': '#804500',
  // 'Nemoci endokrinní, výživy a přeměny látek': '#000000',
  // 'Nemoci krve, krvetvorných orgánů a některé poruchy týkající se mechanismu imunity': '#11a579',
  // 'Nemoci dýchací soustavy': '#e73f74',
  // 'Nemoci trávicí soustavy': '#80ba5a',
  // 'Nemoci močové a pohlavní soustavy': '#e68310',
  // 'Těhotenství, porod a šestinedělí': '#e68310',
  // 'Nemoci kůže a podkožního vaziva': '#008695',
  // 'Nemoci svalové a kosterní soustavy a pojivové tkáně': '#cf1c90',
  // 'Vrozené vady, deformace a chromosomální abnormality': '#f97b72',
  // 'Některé stavy vzniklé v perinatálním období': '#4b4b8f',
  // 'Úmyslné sebepoškození': '#0ebcbf',
  // 'Napadení (útok)': '#5158bb',
  // 'Dopravní nehody': '#9e52aa',
  // 'Ostatní vnější příčiny poranění a otrav': '#eb4776',

  // 'Příznaky, znaky a abnormální klinické a laboratorní nálezy nezařazené jinde': '#f58a5a',
  // 'Nemoci nervové soustavy': '#f2b701',
  // 'Poruchy duševní a poruchy chování': '#f2b701',
  // 'Nemoci oka a očních adnex': '#f2b701',
  // 'Nemoci ucha a bradavkového výběžku': '#f2b701',
  // 'Komplikace zdravotní péče': '#f2b701',
};
